{
    'name': 'Hospital Management ',
    'version': '1.0.0',
    'category': 'Hospital',
    'author': 'La Thanh',
    'website': 'Thereisnooneatall',
    'summary': 'Hospital management system',
    'sequence': -90,
    'description': """Hospital Management System - Created at 9:30 27/4/2023""",
    'depends' : ['mail', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'data/patient.tag.csv',
        'data/patient_tag_data.xml',
        'data/sequence_data.xml',
        'wizard/cancel_appointment_view.xml',
        'views/menu.xml',
        'views/patient_view.xml',
        'views/female_patient_view.xml',
        'views/male_patient_view.xml',
        'views/kid_patient_view.xml',
        'views/appointment_view.xml',
        'views/patient_tag_view.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'lincense': 'LGPL Version 3'
}